import { z } from "zod"

export const productSchema = z.object({
  name: z.string().min(2, "Ürün adı en az 2 karakter olmalı"),
  slug: z.string().optional(),
  shortDesc: z.string().optional(),
  fullDesc: z.string().optional(),
  sku: z.string().optional(),
  barcode: z.string().optional(),
  brandId: z.string().nullable().optional(),
  manufacturer: z.string().optional(),
  originCountry: z.string().optional(),
  priceUsd: z.number().positive("Fiyat sıfırdan büyük olmalı"),
  priceTl: z.number().optional(),
  salePriceUsd: z.number().nullable().optional(),
  salePriceTl: z.number().nullable().optional(),
  saleStart: z.string().nullable().optional(),
  saleEnd: z.string().nullable().optional(),
  vatRate: z.number().int(),
  vatIncluded: z.boolean(),
  stockTracking: z.boolean(),
  stockQty: z.number().int().min(0),
  lowStockThreshold: z.number().int().min(0),
  weight: z.number().nullable().optional(),
  width: z.number().nullable().optional(),
  height: z.number().nullable().optional(),
  depth: z.number().nullable().optional(),
  isFeatured: z.boolean(),
  isNew: z.boolean(),
  isBestSeller: z.boolean(),
  seoTitle: z.string().optional(),
  seoDesc: z.string().optional(),
  status: z.enum(["DRAFT", "PUBLISHED", "PENDING", "HIDDEN"]),
  visibility: z.enum(["PUBLIC", "MEMBERS_ONLY", "PASSWORD_PROTECTED"]),
  publishAt: z.string().nullable().optional(),
  sortOrder: z.number().int(),
  categoryIds: z.array(z.string()).optional(),
  tagIds: z.array(z.string()).optional(),
})

export type ProductInput = z.infer<typeof productSchema>
